def projectPath = new com.eviware.soapui.support.GroovyUtils(context).projectPath //gets the path of the project root
//def file = new File(projectPath+'/Configuration_G3.ini')
//def file = new File(projectPath+'/Configuration_T4.ini')
def file = new File(projectPath+'/soapui.ini')
log.info(":::::::> " + file)
yourData = file.eachLine { line ->
    (value1, value2) = line.tokenize( '=' )
    if(line.contains('BOOKING_SITE_SMART14=')
            || line.contains('mydate=')
            || line.contains('SMART30=')
            || line.contains('SMART14=')
            || line.contains('BOOKING_DATE_SMART14=')
            || line.contains('BOOKING_SITE_SMART30=')
            || line.contains('BASIC=')
            || line.contains('SMART7=')
            || line.contains('BOOKING_SERVICE02_BASIC=')
            || line.contains('BOOKING_DATE_BASIC=')
            || line.contains('dBegin=')
            || line.contains('smart14=')
            || line.contains('SMART2=')
            || line.contains('Date_NBF=')
            || line.contains('BOOKING_SITE_BASIC=')
            || line.contains('SERVICE_NBF=')
            || line.contains('smart2=')
            || line.contains('BOOKING_SERVICE02_SMART07=')
            || line.contains('SITE_NBF=')
            || line.contains('BOOKING_DATE_SMART7=')
            || line.contains('BOOKING_SERVICE_SMART14=')
            || line.contains('BOOKING_SITE_SMART07=')
            || line.contains('smart7=')
            || line.contains('BOOKING_SERVICE_SMART2=')
            || line.contains('DateSmart=')
            || line.contains('BOOKING_DATE_SMART2=')
            || line.contains('BOOKING_SERVICE_SMART30=')
            || line.contains('BOOKING_SERVICE02_SMART2=')
            || line.contains('BOOKING_DATE_SMART30=')
            || line.contains('BOOKING_SITE_SMART2=')
            || line.contains('BOOKING_SERVICE02_SMART30=')
            || line.contains('BOOKING_SERVICE_SMART07=')
            || line.contains('BOOKING_SERVICE_BASIC=')
            || line.contains('BOOKING_SERVICE02_SMART14=')

    ){
        testRunner.testCase.testSuite.project.setPropertyValue(value1,value2);
    }
}